package com.example.dosereminderapp.api.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * This data class represents a medication in the database. It includes the medication's details like name,
 * dosage, frequency, and start date. The data is stored in the "medications" table.
 */
@Entity(tableName = "medications")
data class Medication(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,  // Autogenerated ID
    val name: String,                                  // Name of the medicine
    val quantity: Int,                                 // Amount per dose
    val dosage: String,                                // Dose
    val frequency: String,                             // Frequency (e.g., "2 times a day")
    val time: String,                                  // Specific time (e.g., "08:00", "10:20")
    val dayPart: String,                               // AM or PM
    val startTo: String                                // Fecha de inicio (e.g., "Today" etc)
)